### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NanYan210** [GiantCaiB/LazyShit#1]
C:\Windows\system32>cd C:\Users\YanNan\Desktop\LazyShit-master\bin\Release\netcoreapp3.0\win-x64

C:\Users\YanNan\Desktop\LazyShit-master\bin\Release\netcoreapp3.0\win-x64>LazyAss.exe
Error:
  An assembly specified in the application dependencies manifest (LazyAss.deps.json) was not found:
    package: 'Microsoft.Extensions.Logging.Abstractions', version: '2.1.1'
    path: 'lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll'

**Comment by GiantCaiB** [comment]
下载代码zip, 解压Yuni.zip， 进入publish文件夹直接打开LazyAss.exe 运行。

**Comment by GiantCaiB** [comment]
"* * 9,10,11,13,14,15,16,17 ? * MON,TUE,WED,THU,FRI *" 
只有从9点到17点 周一到周五是会工作的哦， 如果你需要改时间我可以再build一份给你

**Comment by NanYan210** [comment]
我自己去改了program里的cronexpression，然后发现他不点击右键了。。然后我替换回原来的文件，发现也不好使了。。

**Comment by NanYan210** [comment]
啊，我知道了，我12点的时间段是非工作时间，我12加进去，哈哈哈，骚瑞~
